In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

## Making list of all review URLs

In [2]:
base = "https://www.gsmarena.com/apple_iphone_xs-reviews-9318p"
end = ".php"
url_list = []
for i in range(1,20):
    url_list.append(base+str(i)+end)
    
print(url_list)

['https://www.gsmarena.com/apple_iphone_xs-reviews-9318p1.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p2.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p3.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p4.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p5.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p6.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p7.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p8.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p9.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p10.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p11.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p12.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p13.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p14.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p15.php', 'https://www.gsmarena.com/apple_iphone_xs-review

## Function to flatten nested list

In [3]:
flatten = lambda l: [item for sublist in l for item in sublist]

## Applying operations to each URL

In [4]:
all_review = [] ## List to store all the reviews

for url in url_list:
    print(url)
    page=requests.get(url)  ## Retrieve HTML page
    soup = BeautifulSoup(page.content,'html.parser')  ## Parse it by beautiful soup
    review = soup.find_all('p', class_='uopin')
    documents = [x.text.strip().split(".") for x in review] ## List of review on that page
    all_review.extend(documents)

https://www.gsmarena.com/apple_iphone_xs-reviews-9318p1.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p2.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p3.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p4.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p5.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p6.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p7.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p8.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p9.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p10.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p11.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p12.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p13.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p14.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p15.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p16.php
https://www.gsmarena.com/apple_ip

In [5]:
[x.text.strip().split(".") for x in review]

[['Time to let go of iphones for good',
  '',
  '',
  '',
  '',
  " They don't care about one handed use anymore",
  '',
  '',
  ' \r\nRemember how they used to make fun of Samsung for how uncomfortable the original galaxy note is for one handed use (Not just galaxy note, they even made fun of Galaxy s2)',
  '',
  ' And now we have a minimum width of 70+ mm for the smallest iphone',
  '',
  ' and they want us to have carpal tunnel syndrome',
  '',
  ''],
 ['Gj99, 12 Sep 2018Except a thing or two, there is absolutely NO difference between this and iphone X',
  ' \r\nHave the',
  '',
  '',
  ' more"S" editions are mostly incremental updates',
  ' They tend to offer updated specs rather than new ones',
  ' This year the new stuff are the XS Max and XR, not this particular phone!'],
 ["Why all the large phones? \r\nI'm done with apple, the SE is very popular but yet you couldn't make a phone smaller in size? \r\nI don't want to carry a tablet in my back pocket",
  ''],
 ['The only thing I 

In [6]:
all_reviews_flat = flatten(all_review)

all_reviews_flat = [x for x in all_reviews_flat if len(x)>20]

In [7]:
len(all_reviews_flat)

1211

In [8]:
all_reviews_flat[:10]

["Anonymous, 28 Apr 2019Wow! Who cares how much storage it has because you can't use it all if it only has 4gb of ram",
 ' moreI just feel like apple just works on their design mostly',
 ' They try to make it as expensive as they can',
 ' phones cheaper than 1000 dollars do the same or better than the xs',
 " \r\nApple doesn't give a fast charger, they remove the headphone jack, they make the battery slow down so that you upgrade, androids literally do better for customers and the money now",
 'Anonymous, 25 Apr 2019Then came along S10:)))',
 "Anonymous, 28 Apr 2019Wow! Who cares how much storage it has because you can't use it all if it only has 4gb of ram",
 "Wow! Who cares how much storage it has because you can't use it all if it only has 4gb of ram",
 ' Why not buy a oneplus 6t with with 8gb of ram for only $500 or the new blackberry key2 with 6gb of ram and the 56gb of storage?Maybe you would rather pay to screen cast instead of having Wi-Fi direct?',
 'Fer, 24 Apr 2019This evalu

In [9]:
#copy_allpage_mobile_review = pd.DataFrame({"Reviews":all_reviews_flat})
#copy_allpage_mobile_review.to_csv("copy_allpage_mobile_review.csv",index=False)

In [10]:
#pd.set_option('display.max_colWidth',-1)
#copy_allpage_mobile_review.head()

In [62]:
len(copy_allpage_mobile_review)

1199

In [11]:
mobrev = pd.read_excel('newcopy_mobile_review.xlsx')

In [210]:
len(mobrev)

1254

In [12]:
mobrev.shape

(1254, 2)

In [13]:
mobrev.tail()

sentiment                                            Reviews
1249       POS         Apple is 3 years behind Samsung and Huawei
1250       NEG  IMO,why apple a bit fail in china: \r\r\nskyhi...
1251       NEG  Shaun, 22 Mar 2019How about you don't?\r\r\nI'...
1252       NEG   moreCommon! How did you say Iphones SE, 7, 8 ...
1253       NEG  I wish camscanner and many apps running better...

In [14]:
sum(mobrev['sentiment'] == " ")

0

In [15]:
mobrev['sentiment'] = mobrev['sentiment'].astype('str')

In [16]:
from sklearn.model_selection import train_test_split

y = mobrev['sentiment']
X = mobrev.loc[:,'Reviews']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [18]:
print("Lenght of Train" ,len(X_train))
print("Length of Test"  ,len(X_test))

Lenght of Train 1003
Length of Test 251


In [19]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1003,)
(251,)
(1003,)
(251,)


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(min_df=10,ngram_range=(1, 3))
X_train_tf=vectorizer.fit_transform(X_train).toarray()
X_test_tf=vectorizer.transform(X_test).toarray()
print(X_train_tf.shape)
print(X_test_tf.shape)

(1003, 289)
(251, 289)


In [219]:
# from sklearn.decomposition import TruncatedSVD
# svd = TruncatedSVD(n_components=280, n_iter=10, random_state=42)
# X_train_tf_svd = svd.fit_transform(X_train_tf)
# print(svd.explained_variance_ratio_.sum())
# X_test_tf_svd = svd.transform(X_test_tf)

In [21]:
y[:5]

0     POS
1    INFO
2     POS
3     NEG
4     POS
Name: sentiment, dtype: object

In [23]:
#target = pd.DataFrame({"Act":y_train,"Pred":train_nb_preds})

In [25]:
#target.shape

In [27]:
#target.reset_index(drop=True, inplace=True)
# X_train_tf.reset_index(drop=True, inplace=True)

In [28]:
#temp = pd.concat([target,pd.DataFrame(X_train_tf)],ignore_index=True,axis=1)
#temp.to_csv("analyse.csv")

In [29]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report

NBclassifier = GaussianNB()
NBclassifier.fit(X_train_tf, y_train)

## Predictions
train_nb_preds = NBclassifier.predict(X_train_tf)
test_nb_preds = NBclassifier.predict(X_test_tf)

print("Train Accuracy",NBclassifier.score(X_train_tf,y_train))
print(confusion_matrix(y_train,train_nb_preds))
print(classification_report(y_train,train_nb_preds))

#print("test Accuracy",NBclassifier.score(X_test_tf,y_test))
#print(confusion_matrix(y_test,test_nb_preds))
#print(classification_report(y_test,test_nb_preds))


Train Accuracy 0.4935194416749751
[[191 256 212]
 [  0 138  25]
 [  0  15 166]]
             precision    recall  f1-score   support

       INFO       1.00      0.29      0.45       659
        NEG       0.34      0.85      0.48       163
        POS       0.41      0.92      0.57       181

avg / total       0.79      0.49      0.48      1003



In [30]:
#print(classification_report(y_train,train_nb_preds))


In [31]:
# generate classification report
from sklearn import metrics
print(metrics.classification_report(y_test, test_nb_preds))

             precision    recall  f1-score   support

       INFO       0.84      0.23      0.36       163
        NEG       0.27      0.66      0.38        38
        POS       0.29      0.66      0.40        50

avg / total       0.64      0.38      0.37       251



In [32]:
print("test Accuracy",NBclassifier.score(X_test_tf,y_test))

test Accuracy 0.3784860557768924


In [33]:
print(confusion_matrix(y_test,test_nb_preds))

[[37 57 69]
 [ 1 25 12]
 [ 6 11 33]]


In [34]:
print(classification_report(y_test,test_nb_preds))

             precision    recall  f1-score   support

       INFO       0.84      0.23      0.36       163
        NEG       0.27      0.66      0.38        38
        POS       0.29      0.66      0.40        50

avg / total       0.64      0.38      0.37       251



In [35]:
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()
logit.fit(X_train_tf,y_train)

## Predictions
train_logit_preds = logit.predict(X_train_tf)
test_logit_preds = logit.predict(X_test_tf)

print("Train Accuracy",logit.score(X_train_tf,y_train))
print(confusion_matrix(y_train,train_logit_preds))




Train Accuracy 0.732801595214357
[[652   2   5]
 [140  20   3]
 [116   2  63]]


In [36]:
print(classification_report(y_train,train_logit_preds))

             precision    recall  f1-score   support

       INFO       0.72      0.99      0.83       659
        NEG       0.83      0.12      0.21       163
        POS       0.89      0.35      0.50       181

avg / total       0.77      0.73      0.67      1003



In [39]:
print("test Accuracy",logit.score(X_test_tf,y_test))
print(confusion_matrix(y_test,test_logit_preds))
print(classification_report(y_test,test_logit_preds))

test Accuracy 0.6932270916334662
[[161   0   2]
 [ 32   4   2]
 [ 41   0   9]]
             precision    recall  f1-score   support

       INFO       0.69      0.99      0.81       163
        NEG       1.00      0.11      0.19        38
        POS       0.69      0.18      0.29        50

avg / total       0.74      0.69      0.61       251

